$axure.loadCurrentPage({
  "url":"结转-期末结转.html",
  "generationDate":new Date(1462938818583.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b49e122d6c2402a928412c44794b72d",
    "type":"Axure:Page",
    "name":"结转-期末结转",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"63220187816b4aa1adbcbe28e7c494b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce87bb2a4f84afd9463177947eedf4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结转-期末结转/u0.png"}},
{
          "id":"be4401f1d9224a6b9ade0d7b90fbd794",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":40},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结账-凭证列表",
                      "target":{
                        "targetType":"page",
                        "url":"结账-凭证列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f0aa872d844542d9af0dacc95a5317da",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":839,
              "y":130},
            "size":{
              "width":190,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结转-期末凭证",
                      "target":{
                        "targetType":"page",
                        "url":"结转-期末凭证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"40fd4a34407c46b892008e5fa3845d1b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":839,
              "y":280},
            "size":{
              "width":181,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结转-期末凭证",
                      "target":{
                        "targetType":"page",
                        "url":"结转-期末凭证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "63220187816b4aa1adbcbe28e7c494b0":{
      "scriptId":"u0"},
    "0ce87bb2a4f84afd9463177947eedf4a":{
      "scriptId":"u1"},
    "be4401f1d9224a6b9ade0d7b90fbd794":{
      "scriptId":"u2"},
    "f0aa872d844542d9af0dacc95a5317da":{
      "scriptId":"u3"},
    "40fd4a34407c46b892008e5fa3845d1b":{
      "scriptId":"u4"}}});