$axure.loadCurrentPage({
  "url":"修改账套.html",
  "generationDate":new Date(1462938818128.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cdbb74a543754cd68b8985e4c70aeeee",
    "type":"Axure:Page",
    "name":"修改账套",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b9fca97be1c4b02ac825eee477ed507",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0744bc5a64f4fa5988f502ac3e57075",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改账套/u0.png"}},
{
          "id":"295eb3b828c74dfb98b8cc881064e14a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":39},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 企业账套",
                      "target":{
                        "targetType":"page",
                        "url":"企业账套.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2d1b04d84764446785920c64a4337347",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":860},
            "size":{
              "width":512,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 企业账套",
                      "target":{
                        "targetType":"page",
                        "url":"企业账套.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a3f6704f87014296b019e23d829eb62f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":99},
            "size":{
              "width":502,
              "height":51}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改账套-文字录入",
                      "target":{
                        "targetType":"page",
                        "url":"修改账套-文字录入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3b45bbb4e3f64b7587c398278fdc3218",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":160},
            "size":{
              "width":502,
              "height":120}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改账套-不可修改",
                      "target":{
                        "targetType":"page",
                        "url":"修改账套-不可修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7b9fca97be1c4b02ac825eee477ed507":{
      "scriptId":"u0"},
    "c0744bc5a64f4fa5988f502ac3e57075":{
      "scriptId":"u1"},
    "295eb3b828c74dfb98b8cc881064e14a":{
      "scriptId":"u2"},
    "2d1b04d84764446785920c64a4337347":{
      "scriptId":"u3"},
    "a3f6704f87014296b019e23d829eb62f":{
      "scriptId":"u4"},
    "3b45bbb4e3f64b7587c398278fdc3218":{
      "scriptId":"u5"}}});