$axure.loadCurrentPage({
  "url":"跳过科目期初-提示框.html",
  "generationDate":new Date(1462938817732.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fea845350bdb478fb6c422528e2c32b2",
    "type":"Axure:Page",
    "name":"跳过科目期初-提示框",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7b300e0966984dd386b6fd731575c6b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e2fff9f3d7f4d0d80707e7eafd12097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/跳过科目期初-提示框/u0.png"}},
{
          "id":"b7b6d4611d5042c7b52fc008bb6e1c1b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":530},
            "size":{
              "width":220,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记账",
                      "target":{
                        "targetType":"page",
                        "url":"记账.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c86dd6f491864f28bbca91844dbdc0a6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":532},
            "size":{
              "width":220,
              "height":75}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7b300e0966984dd386b6fd731575c6b8":{
      "scriptId":"u0"},
    "0e2fff9f3d7f4d0d80707e7eafd12097":{
      "scriptId":"u1"},
    "b7b6d4611d5042c7b52fc008bb6e1c1b":{
      "scriptId":"u2"},
    "c86dd6f491864f28bbca91844dbdc0a6":{
      "scriptId":"u3"}}});