$axure.loadCurrentPage({
  "url":"选择会计子科目.html",
  "generationDate":new Date(1462938818381.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8acc671a3ba42aa95b12dde1908e861",
    "type":"Axure:Page",
    "name":"选择会计子科目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9ba6f1154c3449b9ec92fd7bb61a8d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e745a3af9441408ac6cbfe61309ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择会计科目",
                      "target":{
                        "targetType":"page",
                        "url":"选择会计科目.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择会计子科目/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d9ba6f1154c3449b9ec92fd7bb61a8d5":{
      "scriptId":"u0"},
    "19e745a3af9441408ac6cbfe61309ff6":{
      "scriptId":"u1"}}});