$axure.loadCurrentPage({
  "url":"结账-凭证列表.html",
  "generationDate":new Date(1462938818481.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"755fc937c5574cb88130cd16cdaea322",
    "type":"Axure:Page",
    "name":"结账-凭证列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f88ab4e8d524b449bb148ce98971eb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673bd2f66ce8476e856ae7ae1b56ac0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/结账-凭证列表/u0.png"}},
{
          "id":"9a5856ffb28842aea44c6ea17d6758fc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":40},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记账",
                      "target":{
                        "targetType":"page",
                        "url":"记账.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"56a2f2549094465ebad64e9461e6721d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":906,
              "y":40},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结账-反结转提示框",
                      "target":{
                        "targetType":"page",
                        "url":"结账-反结转提示框.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"52bb239451b34db8ba4fcc821835262b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":860},
            "size":{
              "width":212,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结转-期末结转",
                      "target":{
                        "targetType":"page",
                        "url":"结转-期末结转.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"02247d92c1e247af9be7b420fa23d9e9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":860},
            "size":{
              "width":280,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结账完成-处理中",
                      "target":{
                        "targetType":"page",
                        "url":"结账完成-处理中.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "8f88ab4e8d524b449bb148ce98971eb9":{
      "scriptId":"u0"},
    "673bd2f66ce8476e856ae7ae1b56ac0f":{
      "scriptId":"u1"},
    "9a5856ffb28842aea44c6ea17d6758fc":{
      "scriptId":"u2"},
    "56a2f2549094465ebad64e9461e6721d":{
      "scriptId":"u3"},
    "52bb239451b34db8ba4fcc821835262b":{
      "scriptId":"u4"},
    "02247d92c1e247af9be7b420fa23d9e9":{
      "scriptId":"u5"}}});