$axure.loadCurrentPage({
  "url":"用户信息下拉框.html",
  "generationDate":new Date(1462938817646.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69ce39ad5211440e9f379f6095ae8286",
    "type":"Axure:Page",
    "name":"用户信息下拉框",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16bdfbd1d59d4714ab4e053ef661aa2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd9d11be3404f79844b215f15786aa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户信息下拉框/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "16bdfbd1d59d4714ab4e053ef661aa2d":{
      "scriptId":"u0"},
    "cfd9d11be3404f79844b215f15786aa4":{
      "scriptId":"u1"}}});