$axure.loadCurrentPage({
  "url":"记账.html",
  "generationDate":new Date(1462938818217.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f0804185f9ea42a1b9c6dd029acda619",
    "type":"Axure:Page",
    "name":"记账",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"92cbe882feda4624858f9a7afc268fa0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b1495562f049298c965d4399fed02d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/记账/u0.png"}},
{
          "id":"cd8ea46175ef41c18cf93a18538b8eec",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":526,
              "y":877},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Reload",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"644f355450294d1c905e67c8cd7b3613",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":877},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我",
                      "target":{
                        "targetType":"page",
                        "url":"我.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"50a52145311c41e789472687bfb670dc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":40},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 企业账套",
                      "target":{
                        "targetType":"page",
                        "url":"企业账套.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ea500c88f1ad436883fe72db31a90f5a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":390},
            "size":{
              "width":290,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记账-新增凭证",
                      "target":{
                        "targetType":"page",
                        "url":"记账-新增凭证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5de560f16d4b46f6bc577729f070954a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":390},
            "size":{
              "width":120,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 模板",
                      "target":{
                        "targetType":"page",
                        "url":"模板.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f29218d7ed7b47f98c91b2a066091129",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":556},
            "size":{
              "width":490,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证列表",
                      "target":{
                        "targetType":"page",
                        "url":"凭证列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b62fdbd9f7db4328aa37b9934cb10933",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":625,
              "y":870},
            "size":{
              "width":60,
              "height":67}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账簿",
                      "target":{
                        "targetType":"page",
                        "url":"账簿.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4c4a7195c6d548bd847c90ceb7dcb241",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":616},
            "size":{
              "width":498,
              "height":54}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结账-凭证列表",
                      "target":{
                        "targetType":"page",
                        "url":"结账-凭证列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "92cbe882feda4624858f9a7afc268fa0":{
      "scriptId":"u0"},
    "46b1495562f049298c965d4399fed02d":{
      "scriptId":"u1"},
    "cd8ea46175ef41c18cf93a18538b8eec":{
      "scriptId":"u2"},
    "644f355450294d1c905e67c8cd7b3613":{
      "scriptId":"u3"},
    "50a52145311c41e789472687bfb670dc":{
      "scriptId":"u4"},
    "ea500c88f1ad436883fe72db31a90f5a":{
      "scriptId":"u5"},
    "5de560f16d4b46f6bc577729f070954a":{
      "scriptId":"u6"},
    "f29218d7ed7b47f98c91b2a066091129":{
      "scriptId":"u7"},
    "b62fdbd9f7db4328aa37b9934cb10933":{
      "scriptId":"u8"},
    "4c4a7195c6d548bd847c90ceb7dcb241":{
      "scriptId":"u9"}}});