$axure.loadCurrentPage({
  "url":"修改凭证.html",
  "generationDate":new Date(1462938818449.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f61edcbf844847ad923792477537ae2f",
    "type":"Axure:Page",
    "name":"修改凭证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1ce924ee24144ec91dce9cd347e5831",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a20778e587d04e8d9caff5ed8f1bcdbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改凭证/u0.png"}},
{
          "id":"f32c70c866644d24bcd07cfcf477938e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":873},
            "size":{
              "width":460,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证列表",
                      "target":{
                        "targetType":"page",
                        "url":"凭证列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"403024e21b2d44fc880c5c82a0addf20",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":38},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 凭证列表",
                      "target":{
                        "targetType":"page",
                        "url":"凭证列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3ee4202bfc594c7caa3b41998b8781e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF4F4F4},
            "location":{
              "x":910,
              "y":810},
            "size":{
              "width":119,
              "height":53},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF4F4F4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d434491bcae45d6a6f6cc048b58c87a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4},
                "location":{
                  "x":910,
                  "y":810},
                "size":{
                  "width":119,
                  "height":53},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF4F4F4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改凭证/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e1ce924ee24144ec91dce9cd347e5831":{
      "scriptId":"u0"},
    "a20778e587d04e8d9caff5ed8f1bcdbd":{
      "scriptId":"u1"},
    "f32c70c866644d24bcd07cfcf477938e":{
      "scriptId":"u2"},
    "403024e21b2d44fc880c5c82a0addf20":{
      "scriptId":"u3"},
    "3ee4202bfc594c7caa3b41998b8781e5":{
      "scriptId":"u4"},
    "3d434491bcae45d6a6f6cc048b58c87a":{
      "scriptId":"u5"}}});