$axure.loadCurrentPage({
  "url":"掌中财税.html",
  "generationDate":new Date(1462938817520.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8b174c86f7984cb7aa80e72ed39012c3",
    "type":"Axure:Page",
    "name":"掌中财税",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cefc5c69ed0a434a8451c2dcc3ace626",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF4F9F5},
{
                  "color":0xFFF4F9F5},
{
                  "color":0xFF82D79D},
{
                  "color":0xFF82D79D}]},
            "location":{
              "x":518,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b17288f6fb0b42c4a8c100cd28d75aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF4F9F5},
{
                      "color":0xFFF4F9F5},
{
                      "color":0xFF82D79D},
{
                      "color":0xFF82D79D}]},
                "location":{
                  "x":518,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/掌中财税/u0.png"}},
{
          "id":"ffe75ac9844240f8a767ed48bd3b2583",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":655,
              "y":305},
            "size":{
              "width":260,
              "height":260},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":204,
                "g":204,
                "b":204,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b22a9c2d61bb4279a567327d5ebc0c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":655,
                  "y":305},
                "size":{
                  "width":260,
                  "height":260},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":204,
                    "g":204,
                    "b":204,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 引导页1",
                      "target":{
                        "targetType":"page",
                        "url":"引导页1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/掌中财税/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cefc5c69ed0a434a8451c2dcc3ace626":{
      "scriptId":"u0"},
    "b17288f6fb0b42c4a8c100cd28d75aba":{
      "scriptId":"u1"},
    "ffe75ac9844240f8a767ed48bd3b2583":{
      "scriptId":"u2"},
    "b22a9c2d61bb4279a567327d5ebc0c9c":{
      "scriptId":"u3"}}});