$axure.loadCurrentPage({
  "url":"明细账-日期弹出框.html",
  "generationDate":new Date(1462938818719.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"021c9e3b067140aca698374b43984fb4",
    "type":"Axure:Page",
    "name":"明细账-日期弹出框",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e8565b7cc6804b9497a3facfd0e3f146",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dbf7650dc664c0aa3d91d0e03d19902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 明细账",
                      "target":{
                        "targetType":"page",
                        "url":"明细账.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/明细账-日期弹出框/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e8565b7cc6804b9497a3facfd0e3f146":{
      "scriptId":"u0"},
    "0dbf7650dc664c0aa3d91d0e03d19902":{
      "scriptId":"u1"}}});