$axure.loadCurrentPage({
  "url":"期初设置.html",
  "generationDate":new Date(1462938817675.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"35e93b56c72b409193f98e3fdab44569",
    "type":"Axure:Page",
    "name":"期初设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"968c04b20a4b4d739f6492d03c48bfa7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8563089b2984942abb8373805476359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/期初设置/u0.png"}},
{
          "id":"0c17ef80da7444f5954d0ef7f9d1436d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":38},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fef0521fcf0d47249be098d4d502993e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":99},
            "size":{
              "width":240,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 增加子级",
                      "target":{
                        "targetType":"page",
                        "url":"增加子级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5915be3935cd4e9284d80be79b6b0420",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":858},
            "size":{
              "width":501,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "968c04b20a4b4d739f6492d03c48bfa7":{
      "scriptId":"u0"},
    "e8563089b2984942abb8373805476359":{
      "scriptId":"u1"},
    "0c17ef80da7444f5954d0ef7f9d1436d":{
      "scriptId":"u2"},
    "fef0521fcf0d47249be098d4d502993e":{
      "scriptId":"u3"},
    "5915be3935cd4e9284d80be79b6b0420":{
      "scriptId":"u4"}}});