$axure.loadCurrentPage({
  "url":"用户登录.html",
  "generationDate":new Date(1462938817581.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"018839a4d39b47bcb17bc942f0a955a6",
    "type":"Axure:Page",
    "name":"用户登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ca6ee94c37c84f4f8314c17c49c28457",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d3f3d6d67fa46138887aabb9b713fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户登录/u0.png"}},
{
          "id":"c9c51dc06fe54473abcb4994b343134b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":290},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新用户",
                      "target":{
                        "targetType":"page",
                        "url":"新用户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c9dbef0d52924f5798cb314012aa1f7a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":290},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 忘记密码",
                      "target":{
                        "targetType":"page",
                        "url":"忘记密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7181880ef6e7471d8c16eb324d7a79c3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":850},
            "size":{
              "width":510,
              "height":87}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择账套",
                      "target":{
                        "targetType":"page",
                        "url":"选择账套.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"82fe96aa0066421882e67db455ece9bb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":950,
              "y":220},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 密码可见",
                      "target":{
                        "targetType":"page",
                        "url":"密码可见.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1271d7f29fbc4610ae47eb121c289131",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":127},
            "size":{
              "width":420,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录-文字录入",
                      "target":{
                        "targetType":"page",
                        "url":"登录-文字录入.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "ca6ee94c37c84f4f8314c17c49c28457":{
      "scriptId":"u0"},
    "9d3f3d6d67fa46138887aabb9b713fc1":{
      "scriptId":"u1"},
    "c9c51dc06fe54473abcb4994b343134b":{
      "scriptId":"u2"},
    "c9dbef0d52924f5798cb314012aa1f7a":{
      "scriptId":"u3"},
    "7181880ef6e7471d8c16eb324d7a79c3":{
      "scriptId":"u4"},
    "82fe96aa0066421882e67db455ece9bb":{
      "scriptId":"u5"},
    "1271d7f29fbc4610ae47eb121c289131":{
      "scriptId":"u6"}}});