$axure.loadCurrentPage({
  "url":"忘记密码.html",
  "generationDate":new Date(1462938817744.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"99f08882bbce4969b2fc4c0a3b6ed220",
    "type":"Axure:Page",
    "name":"忘记密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"952ba5eba0d847098bf7d546b867a97f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea9d32e390f4d6ab0f66bcde31fc0ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u0.png"}},
{
          "id":"db2c9ca6cf1642d2a5a252e8695b9cda",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":38},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户登录",
                      "target":{
                        "targetType":"page",
                        "url":"用户登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1a74a2c659504320b58adb13fa79d857",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":858},
            "size":{
              "width":514,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记账",
                      "target":{
                        "targetType":"page",
                        "url":"记账.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"85493a50c0884774a772c0ea5b0cc029",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":128},
            "size":{
              "width":190,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 获取验证码",
                      "target":{
                        "targetType":"page",
                        "url":"获取验证码_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "952ba5eba0d847098bf7d546b867a97f":{
      "scriptId":"u0"},
    "1ea9d32e390f4d6ab0f66bcde31fc0ea":{
      "scriptId":"u1"},
    "db2c9ca6cf1642d2a5a252e8695b9cda":{
      "scriptId":"u2"},
    "1a74a2c659504320b58adb13fa79d857":{
      "scriptId":"u3"},
    "85493a50c0884774a772c0ea5b0cc029":{
      "scriptId":"u4"}}});