$axure.loadCurrentPage({
  "url":"科目期初.html",
  "generationDate":new Date(1462938817660.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"21bbfcf567af4eb0a988b7c3a10fc5d0",
    "type":"Axure:Page",
    "name":"科目期初",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f6c924a6ca394e1a8a2a1f0b9de4ec1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76cdbd3385e24cec9ab1977b1330d01f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/科目期初/u0.png"}},
{
          "id":"93c5a7620d8e4d9e97ebd9a4eea4e216",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":200},
            "size":{
              "width":529,
              "height":90}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 期初设置",
                      "target":{
                        "targetType":"page",
                        "url":"期初设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5ccae79dd4a54226af46104010e5b2e1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":30},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 跳过科目期初-提示框",
                      "target":{
                        "targetType":"page",
                        "url":"跳过科目期初-提示框.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1d77a4baab764dfd8e813b082d9e0b33",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":810},
            "size":{
              "width":136,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试算平衡",
                      "target":{
                        "targetType":"page",
                        "url":"试算平衡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5371196243544a4b946157c9c128eda5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":856},
            "size":{
              "width":504,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初-账套信息",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初-账套信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "f6c924a6ca394e1a8a2a1f0b9de4ec1f":{
      "scriptId":"u0"},
    "76cdbd3385e24cec9ab1977b1330d01f":{
      "scriptId":"u1"},
    "93c5a7620d8e4d9e97ebd9a4eea4e216":{
      "scriptId":"u2"},
    "5ccae79dd4a54226af46104010e5b2e1":{
      "scriptId":"u3"},
    "1d77a4baab764dfd8e813b082d9e0b33":{
      "scriptId":"u4"},
    "5371196243544a4b946157c9c128eda5":{
      "scriptId":"u5"}}});