$axure.loadCurrentPage({
  "url":"增加子级_1.html",
  "generationDate":new Date(1462938818107.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"528b8597fc9845709006cf35b7fae39c",
    "type":"Axure:Page",
    "name":"增加子级",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f31e401d5d2942c5af015cee402fccaf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":0},
            "size":{
              "width":529,
              "height":940}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baf1edb385384f5ea28ece8a1c5c58ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":529,
                  "height":940}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/增加子级_1/u0.png"}},
{
          "id":"b0330d8d3e0a48aa9f5673ad8f251388",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":38},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会计科目",
                      "target":{
                        "targetType":"page",
                        "url":"会计科目.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9a6c0cef285546f6aa2e40758ec9d645",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":98},
            "size":{
              "width":253,
              "height":62}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 科目期初",
                      "target":{
                        "targetType":"page",
                        "url":"科目期初_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"dd3a59aae75c4a92a3f8b031fe54e84b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":856},
            "size":{
              "width":513,
              "height":80}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会计科目",
                      "target":{
                        "targetType":"page",
                        "url":"会计科目.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "f31e401d5d2942c5af015cee402fccaf":{
      "scriptId":"u0"},
    "baf1edb385384f5ea28ece8a1c5c58ac":{
      "scriptId":"u1"},
    "b0330d8d3e0a48aa9f5673ad8f251388":{
      "scriptId":"u2"},
    "9a6c0cef285546f6aa2e40758ec9d645":{
      "scriptId":"u3"},
    "dd3a59aae75c4a92a3f8b031fe54e84b":{
      "scriptId":"u4"}}});